local opt = vim.opt
opt.relativenumber = true
opt.number = true
opt.undofile = true
opt.expandtab = true
opt.shiftwidth = 4
opt.tabstop = 4
opt.softtabstop = 4
opt.smarttab = true
opt.smartindent = true
opt.autoindent = true
opt.breakindent = true
opt.whichwrap = "b,s,h,l,<,>,[,]"
opt.wrap = false
opt.ignorecase = true
opt.smartcase = true
opt.incsearch = true
opt.hlsearch = true
opt.cursorline = true
opt.mouse = "a"
opt.termguicolors = true
opt.background = "dark"
opt.signcolumn = "yes"
opt.backspace = "indent,eol,start,nostop"
opt.splitright = true
opt.splitbelow = true
opt.swapfile = true
opt.backup = true
opt.backupcopy = "yes"
opt.backupext = ".tmp"
opt.backupdir = vim.fn.stdpath("state") .. "/backup"
opt.undofile = true
opt.undodir = vim.fn.stdpath("state") .. "/undo"
opt.showmode = false
opt.splitbelow = true
opt.splitright = true
opt.completeopt = { "menuone", "noselect" }
opt.updatetime = 50
opt.timeoutlen = 300
opt.cursorline = true
opt.scrolloff = 1
opt.sidescrolloff = 10
opt.colorcolumn = "80"
opt.list = true
opt.listchars = {
	eol = "⤶",
	nbsp = "˾",
	space = "∙",
	tab = ">-",
	trail = "●",
}
opt.conceallevel = 1
opt.clipboard = "unnamedplus"
opt.cmdheight = 0
opt.cmdwinheight = 10
opt.fileencoding = "utf-8"
opt.pumheight = 10
opt.guifont = "monospaced:h17"

vim.g.loaded_ruby_provider = 0
vim.g.ruby_host_prof = "/usr/sbin/ruby"
vim.g.loaded_perl_provider = 0
vim.g.perl_host_prof = "/usr/sbin/perl"
vim.g.loaded_python3_provider = 0
vim.g.python3_host_prof = "/usr/sbin/python3"
