return {
	cmd = {
		"clangd",
		"--background-index",
		"--clang-tidy",
		"--header-insertion=iwyu",
		"--fallback-style=none",
		"--completion-style=detailed",
		"--function-arg-placeholders=true",
		"--log=verbose",
	},
	filetypes = { "c", "cpp", "objc", "objcpp", "cuda" },
	root_markers = {
		".clangd",
		".clang-tidy",
		".clang-format",
		"compile_commands.json",
		"compile_flags.txt",
		"configure.ac",
		".git",
		"CMakeList.txt",
		"CMake*",
		".build.yml",
		".build.yaml",
		".hg",
		".hgignore",
		".hgtags",
		"meson.build",
		"meson_options.txt",
	},
	single_file_support = true,
	capabilities = get_complete_capabilities(),
	on_attach = attach,
}
