return {}
-- return {
--   {
--     "folke/lazydev.nvim",
--     ft = "lua", -- only load on lua files
--     opts = {
--       library = {
--         -- See the configuration section for more details
--         -- Load luvit types when the `vim.uv` word is found
--         { path = "${3rd}/luv/library", words = { "vim%.uv" } },
--       },
--     },
--   },
--   { -- optional cmp completion source for require statements and module annotations
--     "hrsh7th/nvim-cmp",
--     opts = function(_, opts)
--       opts.sources = opts.sources or {}
--       table.insert(opts.sources, {
--         name = "lazydev",
--         group_index = 0, -- set group index to 0 to skip loading LuaLS completions
--       })
--     end,
--   },
--   -- add blink.compat
--   {
--     'saghen/blink.compat',
--     -- use the latest release, via version = '*', if you also use the latest release for blink.cmp
--     version = '*',
--     -- lazy.nvim will automatically load the plugin when it's required by blink.cmp
--     lazy = true,
--     -- make sure to set opts so that lazy.nvim calls blink.compat's setup
--     opts = {},
--   },
--   -- add blink.cmp
--   {
--     "Saghen/blink.cmp",
--     dependencies = {
--       'rafamadriz/friendly-snippets',
--       { "L3MON4D3/LuaSnip", version = 'v2.*' },
--     },
--     version = "*",
--
--     ---@module 'blink.cmp'
--     ---@type blink.cmp.Config
--     opts = {
--       signature = { enabled = true },
--       -- keymap = { preset = 'default' },
--       keymap = {
--         preset = 'none',
--         ["<S-Tab>"] = { "select_prev", "fallback" },
--         ["<Tab>"] = { "select_next", "fallback" },
--         ["<S-Enter>"] = {
--           function(cmp)
--             if cmp.snippet_active() then
--               return cmp.accept()
--             else
--               return cmp.select_and_accept()
--             end
--           end,
--         },
--       },
--       appearance = {
--         nerd_font_variant = "mono",
--       },
--       snippets = { preset = 'luasnip' },
--       sources = {
--         default = { "lazydev", "lsp", "snippets", "path", "buffer" },
--         providers = {
--           lazydev = {
--             name = "LazyDev",
--             module = "lazydev.integrations.blink",
--             -- make lazydev completions top priority (see `:h blink.cmp`)
--             score_offset = 3,
--           },
--         },
--       },
--       fuzzy = {
--         implementation = "prefer_rust_with_warning",
--         prebuilt_binaries = {
--           download = true,
--           ignore_version_mismatch = true,
--         }
--       },
--     },
--     opts_extend = { "sources.default" }
--   },
-- }
