return {
--   "rose-pine/neovim",
--   lazy = false,
--   priority = 1000,
--   name = "rose-pine",
--   config = function()
--     require("rose-pine").setup({
--       variant = "moon",
--       dim_inactive_window = false,
--       extend_background_behind_borders = true,
--
--       integrations = {
--         cmp = true,
--         gitsigns = true,
--         harpoon = true,
--         illuminate = true,
--         indent_blankline = {
--           enabled = false,
--           scope_color = "sapphire",
--           colored_indent_levels = false,
--         },
--         mason = true,
--         native_lsp = { enabled = true },
--         notify = true,
--         nvimtree = true,
--         neotree = true,
--         symbols_outline = true,
--         telescope = true,
--         treesitter = true,
--         treesitter_context = true,
--       },
--
--       enable = {
--         terminal = true,
--         legacy_highlights = true,
--         migrations = true,
--       },
--
--       styles = {
--         bold = true,
--         italic = true,
--         transparency = false,
--       },
--
--       groups = {
--         border = "muted",
--         link = "iris",
--         panel = "surface",
--
--         error = "love",
--         hint = "iris",
--         info = "foam",
--         note = "pine",
--         todo = "rose",
--         warn = "gold",
--
--         git_add = "foam",
--         git_change = "rose",
--         git_delete = "love",
--         git_dirty = "rose",
--         git_ignore = "muted",
--         git_merge = "iris",
--         git_rename = "pine",
--         git_stage = "iris",
--         git_text = "rose",
--         git_untracked = "subtle",
--
--         h1 = "iris",
--         h2 = "foam",
--         h3 = "rose",
--         h4 = "gold",
--         h5 = "pine",
--         h6 = "foam",
--       },
--
--       highlight_groups = {
--         -- Comment = { fg = "foam" },
--         -- VertSplit = { fg = "muted", bg = "muted" },
--       },
--
--       before_highlight = function(group, highlight, palette)
--         -- Disable all undercurls
--         -- if highlight.undercurl then
--         --     highlight.undercurl = false
--         -- end
--         --
--         -- Change palette colour
--         -- if highlight.fg == palette.pine then
--         --     highlight.fg = palette.foam
--         -- end
--       end,
--     })
--
--     vim.cmd("colorscheme rose-pine")
--   end,
}
